language: generic
services: docker
script:
- docker run --rm -v "$PWD":"/repo" -w "/repo" volkerraschek/container-latex:latest-ubuntu20.04
  /bin/sh -c "apt-get update && apt-get install -y unzip curl && mkdir -p /usr/share/xindy/lang/persian/
  && curl -L -o /usr/share/xindy/lang/persian/variant3-utf8-lang.xdy http://mirrors.ctan.org/indexing/xindy/contrib/xindy-persian/variant3-utf8-lang.xdy
  && curl -L -o /usr/share/xindy/lang/persian/variant3-utf8.xdy http://mirrors.ctan.org/indexing/xindy/contrib/xindy-persian/variant3-utf8.xdy
  && latexmk"
deploy:
  provider: releases
  token:
    secure: dAmZtUTqL6W7y6JuiW9O4/407tqeWApF8a8bnzFd4XkOm67ZTXGtLnraAp8MkwsSqunFLq4Z7XLWSqNNg0FSgcs31pZmIPG6L4KfpQT2P8fbCoWB90Eieh31hfqjFkmsgBAZnTtxd1aBaI094FaOqJQM8EZNLfDIMDWoZmJAnqOVyoKi/X0Dv8amuGnlsKHt1QFl0la/JlIOb0umS3DSYgLLshIyp/8UqnVT4FgYXHsRYJbzQkixe1feoF+glCECPFiqOmNs9sqUfDunbu5XSvqbtrkN2evs6+05e1j578kCo3aN+OLbOZYxlXuJE/UKaXxPeZdI90VgX/WnL0An5DiYzdOgw5nOe3vw57TdJ2+3sQfjDG5xGMlOZuM2QPTYSx71YZLyTj6l963FhK70HOt2y0OPg05V6HZrBVkQNwReAuHl5lVqSHSOiMKH+ImYMsK1gnPiBLTPmflABLf6l/GFkGmVWEtHma8dgHWHgGqn4uhKQcz52Imf4TM89zaWqJ32xaZ5gwGwga8VaaAYRkhkg/sLpdgARwRj6e4SjqHr0oPruVwHDSqCcIFNlov0Q/TcH4KY88jwWogFttYbdkqFM4lPnX6ARhsFca0hVTOlWoXeDiXg9hNoma5Mf4cmoXYG1nu+UYf/JGdA/jVr4UMLfQ6U3VLHF+1J3Wt4Ijo=
  file: "*.pdf"
  cleanup: false
  on:
    repo: sinamomken/tehran-thesis
    tags: true
